In [2]:
from PyLQR.sim import KDLRobot
from PyLQR.system import PosOrnPlannerSys, PosOrnKeypoint
from PyLQR.solver import BatchILQRCP, BatchILQR, ILQRRecursive
from PyLQR.utils import primitives, PythonCallbackMessage

import numpy as np
import matplotlib.pyplot as plt
import cv2
from tqdm import tqdm

import logging
import sys

from scipy.spatial.transform import Rotation 

from cv_bridge import CvBridge, CvBridgeError

sys.path.append("/home/vdrame/catkin_ws/src/py_panda/PyPanda")
from PyPanda import Robot
from PyPanda import Utils

from utils.camera_utils import RealCamera, RealCameraROS
from utils.transform_utils import *
from utils.iLQR_wrapper import iLQR
from utils.visualisation_utils import depth2pc
from utils.ROS_utils import generate_grasps_client, format_pointcloud_msg, run_action, get_camera_pose, gridRegistrator

import argparse
from scipy.spatial.transform import Rotation

import time

from contact_grasp.srv import contactGraspnetPointcloud2, contactGraspnetPointcloud2Response

import json
import rospy
from cv_bridge import CvBridge, CvBridgeError
from sensor_msgs import point_cloud2
from sensor_msgs.msg import PointField, CameraInfo, Image, PointCloud2
from std_msgs.msg import Header
from geometry_msgs.msg import PoseArray, Pose
import message_filters

import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


INFO - 2023-06-21 15:06:37,824 - utils - NumExpr defaulting to 8 threads.
INFO - 2023-06-21 15:06:38,376 - base_toolkit - Could not load plugin 'qt' from 'pyface.ui.qt.init'
INFO - 2023-06-21 15:06:38,377 - base_toolkit - No pyface.toolkits plugin could be loaded for qt
INFO - 2023-06-21 15:06:38,377 - base_toolkit - Could not load traitsui.toolkits plugin 'qt' from 'traitsui.qt4'
INFO - 2023-06-21 15:06:38,378 - base_toolkit - Could not load traitsui.toolkits plugin 'wx' from 'traitsui.wx'
INFO - 2023-06-21 15:06:38,490 - base_toolkit - Could not load plugin 'qt4' from 'pyface.ui.qt.init'
INFO - 2023-06-21 15:06:38,492 - base_toolkit - No pyface.toolkits plugin could be loaded for qt4
INFO - 2023-06-21 15:06:38,492 - base_toolkit - Could not load traitsui.toolkits plugin 'qt4' from 'traitsui.qt4'


In [3]:
def restart_controller(rbt, homing=False):
    eef_pos, eef_quat = [], []
    rbt.stop_controller()
    rbt.error_recovery()
    rbt.switch_controller("joint_velocity_controller")
    if homing:
        rbt.gripper.homing()

In [4]:
bridge = CvBridge()
try:
    rospy.init_node("python_node",anonymous=True)
except:
    print("rospy already initialized")

# dispose_pos = np.array([dim, 0.66, 0.1])
# dispose_orn_wxyz = np.array([0, 1, 0.35, 0])

# Load robot
rbt = Robot("panda", use_gripper=True)
traj_gen = iLQR(rbt)

image_sub = message_filters.Subscriber("/grid_generator/disposability_grid", Image)
pose_sub = message_filters.Subscriber("/grid_generator/Posearray_pub", PoseArray)
ts = message_filters.TimeSynchronizer([pose_sub, image_sub], 1)
grid = gridRegistrator(rbt)
ts.registerCallback(grid.callback)

camera_connexion = "ROS"
if camera_connexion == "ROS":
    camera = RealCameraROS()
    intrinsic, distortion = camera.getIntrinsic()
elif camera_connexion == "pyWrapper":
    camera = RealCamera()
    camera.start()
    #retrieve image and depth to initialise camera, otherwise image is very dark
    for i in range(15):
        rgb, depth_image, depth_scale = camera.get_rgb_depth()
else:
    raise Exception("Please choose a valid camera connexion method: ROS or pyWrapper")

difference between iLQR model ee and real robot ee
quat (zyzw) :[ 4.2164770e-06 -1.1110131e-07 -1.2038387e-06  1.0000000e+00]
pos:[ 3.28867958e-07 -6.94548414e-07  3.99218198e-07]
Camera topic found


In [5]:
restart_controller(rbt)


[WARN] [1687352805.642083]: No controllers are running


In [6]:
def draw_triangle(dim=0.1, color=[1, 0, 0]):
    halfdim=dim/2
    points = [
        [0, 0, 0],
        [-halfdim, -halfdim, dim],
        [halfdim, -halfdim, dim],
        [halfdim, halfdim, dim],
        [-halfdim, halfdim, dim],

    ]
    lines = [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 1],

    ]
    colors = [color for i in range(len(lines))]
    line_set = o3d.geometry.LineSet(
        points=o3d.utility.Vector3dVector(points),
        lines=o3d.utility.Vector2iVector(lines),
    )
    line_set.colors = o3d.utility.Vector3dVector(colors)
    return line_set

ls = draw_triangle()
o3d.visualization.draw_geometries([ls])

In [38]:
#load pos and orn from json file
with open('config/views_pos.json') as json_file:
    views_pos = json.load(json_file)

pos_dif = 1000
keys = views_pos.keys()
angle_range = [-140, 40]
pc_fused = []
pc_colors_fused = []
reference_pose = np.eye(4)
plot_coordinate = []
for view_idx, key in enumerate(keys):
# while (not detected or not detected_with_collision):
    horizon = 30
    if abs(np.sum(np.array(rbt.model.ee_pos_rel()) - np.array(views_pos[key]["pos"]))) > 0.01:
        view_jpos, view_x_pos, view_U, view_Ks, view_ds, pos_dif, orn_dif = traj_gen.direct_trajectory(rbt.q, rbt.dq, views_pos[key]["pos"], views_pos[key]["orn_wxyz"], horizon)

        if pos_dif > 0.035:
            print("Trajectory could not reach view continue to next view")
            continue

        view_U = np.array(view_U)
        success, idx, eef_pos, eef_quat = run_action(rbt, view_U, 20)
        rbt.active_controller.send_command(np.zeros(7))
        time.sleep(0.15)
    else:
        print( np.sum(np.array(rbt.model.ee_pos_rel()) - np.array(views_pos[key]["pos"])))
        print(np.array(views_pos[key]["pos"]))
        print(key)
    
    rbg_cv, depth_cv, depth_scale = camera.get_rgb_depth()
    depth_cv = depth_cv * depth_scale
 
    current_pose = get_camera_pose(rbt, ee_depth=-0.10340-0.005)

    if view_idx == 0:
        init_pos = rbt.model.ee_pos_rel()
        init_orn_wxyz = rbt.model.ee_orn_rel()
        reference_pose = get_camera_pose(rbt, ee_depth=-0.10340-0.005)
        depth_init = depth_cv
        rgb_init = rbg_cv
        pc_fused, pc_colors_fused = depth2pc(depth_init, intrinsic, rgb_init)
        pc_fused, pc_colors_fused = regularize_pc(pc_fused, pc_colors_fused, 
                                                  downsampling_method="voxel", voxel_size=0.005,
                                                  outlier_filtering_method="radius", radius_param_arg=[25, 0.015])
    else:
        pc_fused, pc_colors_fused = add_view2pc(pc_fused, pc_colors_fused, reference_pose, current_pose, new_gbr=rbg_cv, 
                                                new_depth=depth_cv, cam_intrisic=intrinsic, regularize=True, voxel_size=0.005)

    coordinate = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1)
    coordinate_line = draw_triangle(color=[1,0,0])

    coordinate_line.transform(current_pose)
    coordinate.transform(current_pose)
    plot_coordinate.append(coordinate)
    plot_coordinate.append(coordinate_line)

    print(plot_coordinate)
    pc_o3d = o3d.geometry.PointCloud()
    pc_o3d.points = o3d.utility.Vector3dVector(pc_fused)
    pc_o3d.colors = o3d.utility.Vector3dVector(pc_colors_fused/255)
    coordinate = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1)
    # coordinate.translate([0,0 , 0.4])
    pc_o3d.transform(reference_pose)
    to_draw = plot_coordinate.copy()
    to_draw.append(pc_o3d)
    o3d.visualization.draw_geometries(to_draw)
    if view_idx == 2:
        break

Downsampling time: 0.7115039825439453s, Filtering time: 0.020446062088012695s
[TriangleMesh with 1134 points and 2240 triangles., LineSet with 8 lines.]
Downsampling time: 0.13733530044555664s, Filtering time: 0.0962061882019043s
[TriangleMesh with 1134 points and 2240 triangles., LineSet with 8 lines., TriangleMesh with 1134 points and 2240 triangles., LineSet with 8 lines.]
Downsampling time: 0.13754487037658691s, Filtering time: 0.2199246883392334s
[TriangleMesh with 1134 points and 2240 triangles., LineSet with 8 lines., TriangleMesh with 1134 points and 2240 triangles., LineSet with 8 lines., TriangleMesh with 1134 points and 2240 triangles., LineSet with 8 lines.]


In [39]:
intrinsic
K=np.zeros((3,4))
K[:3,:3]=intrinsic
K

array([[915.73510742,   0.        , 650.41772461,   0.        ],
       [  0.        , 916.14764404, 356.6946106 ,   0.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ]])

In [40]:
current_pose

array([[ 0.36207937, -0.80969834,  0.46183024,  0.03713808],
       [-0.29576484, -0.56964052, -0.76683309,  0.59482141],
       [ 0.88398064,  0.14106132, -0.44573538,  0.16622674],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [41]:
pt = np.asarray(pc_o3d.points)
# pt = pt/pt[2]
pt = np.append(pt, np.ones((pt.shape[0], 1)), axis=1)
pt.shape

(56298, 4)

In [78]:
uv = K@current_pose@pt.T

In [79]:
uv = uv/uv[2]
print(uv.T[0])
uv = uv.T[:,:2].astype(int)

[5.97670275e+03 2.83267563e+03 1.00000000e+00]


In [83]:
uv[10]

array([5381, 3036])

In [81]:
np.unique(uv)

array([-580, -564, -563, ..., 6001, 6016, 6032])

In [50]:
dist = np.array([0, 0, 0, 0])
o =cv2.projectPoints(np.asarray(pc_o3d.points), current_pose[:3,:3], current_pose[:3,3], intrinsic, distortion)